// web/src/lib/components/footer.svelte
<footer class="w-full bg-zinc-950 px-6 py-8 text-white">
	<div class="container mx-auto flex flex-col space-y-6">
		<!-- Main footer content -->
		<div class="flex flex-col items-center justify-between space-y-6 md:flex-row md:space-y-0">
			<!-- Left side with brand info -->
			<div class="text-center md:text-left">
				<p class="mb-2">
					Made with love by <a
						href="https://sipacid.com"
						target="_blank"
						rel="noopener noreferrer"
						class="text-purple-400 transition duration-200 hover:text-purple-300">Eve</a
					>
				</p>
			</div>

			<!-- Center with links -->
			<div class="flex flex-wrap justify-center gap-x-8">
				<a href="/faq" class="text-gray-300 transition duration-200 hover:text-purple-400">FAQ</a>
				<a href="/support" class="text-gray-300 transition duration-200 hover:text-purple-400"
					>Support</a
				>
				<a href="/privacy" class="text-gray-300 transition duration-200 hover:text-purple-400"
					>Privacy</a
				>
			</div>

			<!-- Right side with social links -->
			<div class="flex space-x-4">
				<a
					href="https://github.com/sipacid"
					target="_blank"
					rel="noopener noreferrer"
					class="text-gray-400 transition duration-200 hover:text-purple-400"
					aria-label="GitHub"
				>
					<svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
						<path
							fill-rule="evenodd"
							d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
							clip-rule="evenodd"
						/>
					</svg>
				</a>
				<a
					href="https://x.com/meowingeve"
					target="_blank"
					rel="noopener noreferrer"
					class="text-gray-400 transition duration-200 hover:text-purple-400"
					aria-label="Twitter"
				>
					<svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
						<path
							d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"
						/>
					</svg>
				</a>
			</div>
		</div>

		<!-- Copyright line -->
		<div class="text-center text-sm text-gray-400">
			<p>© 2025 Asthmaphobia. All rights reserved.</p>
		</div>
	</div>
</footer>

// website-del/components/Footer.tsx
import React from 'react';

export default function Footer() {
  return (
    <footer className="w-full bg-gradient-to-b from-zinc-950 to-black px-6 py-12 text-white shadow-lg">
      <div className="container mx-auto flex flex-col space-y-8">
        {/* Logo section */}
        <div className="flex justify-center mb-4">
          <h2 className="text-2xl font-bold text-purple-400">Asthmaphobia</h2>
        </div>
        
        {/* Main footer content */}
        <div className="flex flex-col items-center justify-between space-y-8 md:flex-row md:space-y-0">
          {/* Left side with brand info */}
          <div className="text-center md:text-left">
            <p className="mb-3 font-medium">
              Made with 💜 by <a
                href="https://sipacid.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-purple-400 transition duration-300 hover:text-purple-300 hover:underline">Eve</a>
            </p>
            <p className="text-sm text-gray-400">Enhancing your ghost hunting experience</p>
          </div>

          {/* Center with links */}
          <div className="flex flex-wrap justify-center gap-x-10 gap-y-4">
            <a href="/faq" className="relative text-gray-300 transition duration-300 hover:text-purple-400 group">
              <span>FAQ</span>
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-purple-400 transition-all duration-300 group-hover:w-full"></span>
            </a>
            <a href="/support" className="relative text-gray-300 transition duration-300 hover:text-purple-400 group">
              <span>Support</span>
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-purple-400 transition-all duration-300 group-hover:w-full"></span>
            </a>
            <a href="/privacy" className="relative text-gray-300 transition duration-300 hover:text-purple-400 group">
              <span>Privacy</span>
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-purple-400 transition-all duration-300 group-hover:w-full"></span>
            </a>
            <a href="/terms" className="relative text-gray-300 transition duration-300 hover:text-purple-400 group">
              <span>Terms</span>
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-purple-400 transition-all duration-300 group-hover:w-full"></span>
            </a>
          </div>

          {/* Right side with social links */}
          <div className="flex space-x-5">
            <a
              href="https://github.com/sipacid"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 transition duration-300 hover:text-purple-400 transform hover:scale-110"
              aria-label="GitHub"
            >
              <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path
                  fillRule="evenodd"
                  d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                  clipRule="evenodd"
                />
              </svg>
            </a>
            <a
              href="https://x.com/meowingeve"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 transition duration-300 hover:text-purple-400 transform hover:scale-110"
              aria-label="Twitter"
            >
              <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path
                  d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"
                />
              </svg>
            </a>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-zinc-800 my-2 w-full opacity-50"></div>

        {/* Copyright line */}
        <div className="text-center text-sm text-gray-400 flex flex-col md:flex-row justify-between items-center gap-4">
          <p>© {new Date().getFullYear()} Asthmaphobia. All rights reserved.</p>
          <p className="text-xs">
            <span className="text-purple-500">Not affiliated</span> with Kinetic Games or Phasmophobia
          </p>
        </div>
      </div>
    </footer>
  );
}
