// web/src/lib/components/FaqItem.svelte
<script lang="ts">
	let { question, answer } = $props();
	let isOpen = $state(false);

	function toggle() {
		isOpen = !isOpen;
	}
</script>

<div
	class="overflow-hidden rounded-xl border border-zinc-800/50 bg-zinc-900/50 backdrop-blur-sm"
	itemscope
	itemprop="mainEntity"
	itemtype="https://schema.org/Question"
>
	<button
		class="flex w-full items-center justify-between px-6 py-4 text-left text-white focus:ring-2 focus:ring-purple-500 focus:outline-none focus:ring-inset"
		onclick={toggle}
		aria-expanded={isOpen}
		aria-controls="faq-answer-{question.replace(/\s+/g, '-').toLowerCase()}"
	>
		<h3 class="text-lg font-medium" itemprop="name">{question}</h3>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="h-6 w-6 text-purple-400 transition-transform duration-200 {isOpen ? 'rotate-180' : ''}"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
		>
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
		</svg>
	</button>

	{#if isOpen}
		<div
			class="px-6 pb-4 text-zinc-300"
			id="faq-answer-{question.replace(/\s+/g, '-').toLowerCase()}"
			itemscope
			itemprop="acceptedAnswer"
			itemtype="https://schema.org/Answer"
		>
			<div itemprop="text">
				{answer}
			</div>
		</div>
	{/if}
</div>

// website/components/FAQItem.tsx
'use client';
import { useState, useId, useRef, useEffect } from 'react';

interface FAQItemProps {
  question: string;
  answer: string;
}

export default function FAQItem({ question, answer }: FAQItemProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [height, setHeight] = useState(0);
  const contentRef = useRef<HTMLDivElement>(null);
  const uniqueId = useId();
  const headingId = `faq-question-${uniqueId}`;
  const panelId = `faq-answer-${uniqueId}`;

  // Measure content height when it changes or when isOpen changes
  useEffect(() => {
    if (isOpen && contentRef.current) {
      setHeight(contentRef.current.scrollHeight);
    } else {
      setHeight(0);
    }
  }, [isOpen]);

  return (
    <div 
      itemScope 
      itemProp="mainEntity" 
      itemType="https://schema.org/Question"
      className="rounded-xl border border-zinc-800/50 bg-zinc-900/50 overflow-hidden transition-colors duration-200 hover:border-purple-600/30"
    >
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full cursor-pointer items-center justify-between p-6 text-left text-white"
        aria-expanded={isOpen}
        aria-controls={panelId}
      >
        <h3 
          id={headingId}
          itemProp="name" 
          className="font-medium"
        >
          {question}
        </h3>
        <span 
          className={`ml-6 flex-shrink-0 text-purple-400 transform transition-transform duration-300 ${isOpen ? 'rotate-180' : 'rotate-0'}`}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M19 9l-7 7-7-7"
            />
          </svg>
        </span>
      </button>
      
      <div 
        className="overflow-hidden transition-all duration-300 ease-in-out"
        style={{ height: `${height}px` }}
      >
        <div 
          ref={contentRef}
          itemScope 
          itemProp="acceptedAnswer" 
          itemType="https://schema.org/Answer"
          className="px-6 pb-6 pt-0"
          id={panelId}
          role="region"
          aria-labelledby={headingId}
        >
          <div 
            className={`text-zinc-400 transform transition-all duration-300 ${isOpen ? 'translate-y-0 opacity-100' : '-translate-y-3 opacity-0'}`}
          >
            <p itemProp="text">{answer}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
