// website-del/components/Header.tsx
"use client";

import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
} from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { User } from "@/db/schema";

// Move navItems outside component to avoid recreation on each render
const NAV_ITEMS = [
  { path: "/", label: "Home" },
  { path: "/dashboard", label: "Dashboard", requiresAuth: true },
  { path: "/features", label: "Features" },
];

interface HeaderProps {
  user?: User;
}

function HeaderComponent({ user }: HeaderProps) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);
  const profileRef = useRef<HTMLDivElement>(null);
  const mobileMenuRef = useRef<HTMLDivElement>(null);
  const pathname = usePathname();
  const isScrolledRef = useRef(false); // Reference to track current scroll state

  // Handle scroll effect with optimization to prevent unnecessary re-renders
  useEffect(() => {
    const handleScroll = () => {
      const shouldBeScrolled = window.scrollY > 10;
      // Only update state if the value has actually changed
      if (isScrolledRef.current !== shouldBeScrolled) {
        isScrolledRef.current = shouldBeScrolled;
        setIsScrolled(shouldBeScrolled);
      }
    };

    // Initial check
    handleScroll();

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Handle outside clicks for profile dropdown
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        profileRef.current &&
        !profileRef.current.contains(event.target as Node)
      ) {
        setIsProfileOpen(false);
      }
      if (
        mobileMenuRef.current &&
        !mobileMenuRef.current.contains(event.target as Node) &&
        !(event.target as Element).closest("[data-menu-toggle]")
      ) {
        setIsMenuOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Memoize isActive function
  const isActive = useCallback(
    (path: string) => {
      if (path === "/" && pathname !== "/") return false;
      return pathname === path || pathname.startsWith(`${path}/`);
    },
    [pathname]
  );

  // Filter nav items based on auth status
  const visibleNavItems = useMemo(
    () => NAV_ITEMS.filter((item) => !item.requiresAuth || user),
    [user]
  );

  return (
    <header
      className={`fixed top-0 left-0 z-50 w-full transition-all duration-300 ${
        isScrolled ? "bg-zinc-900/95 shadow-lg" : "bg-zinc-950/80"
      } backdrop-blur-md`}
    >
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <div className="flex shrink-0 items-center">
            <Link href="/" className="group flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-purple-500 to-purple-700 text-white transition-all group-hover:from-purple-400 group-hover:to-purple-600">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-5 w-5"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <span className="text-lg font-bold tracking-tight">
                <span className="bg-gradient-to-r from-purple-400 to-purple-600 bg-clip-text text-transparent">
                  Asthma
                </span>
                <span>phobia</span>
              </span>
            </Link>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden md:block">
            <ul className="flex items-center space-x-1">
              {visibleNavItems.map((item) => (
                <li key={item.path}>
                  <Link
                    href={item.path}
                    className={`relative px-4 py-2 text-sm font-medium transition-colors duration-200 ${
                      isActive(item.path)
                        ? "text-purple-400"
                        : "text-gray-300 hover:text-white"
                    }`}
                  >
                    {item.label}
                    {isActive(item.path) && (
                      <span className="absolute bottom-0 left-0 h-0.5 w-full bg-purple-500"></span>
                    )}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* Right side - Auth actions */}
          <div className="flex items-center gap-3">
            {user ? (
              <div className="relative" ref={profileRef}>
                <button
                  onClick={() => setIsProfileOpen(!isProfileOpen)}
                  className="flex items-center gap-2 rounded-full bg-zinc-800/70 px-3 py-1.5 text-sm transition hover:bg-zinc-700/80 hover:shadow-md"
                  aria-expanded={isProfileOpen}
                >
                  <div className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-purple-500 to-purple-700 text-xs font-medium shadow">
                    {user.username.charAt(0).toUpperCase()}
                  </div>
                  <span className="hidden sm:inline">{user.username}</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className={`h-4 w-4 transition-transform duration-200 ${
                      isProfileOpen ? "rotate-180" : ""
                    }`}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                </button>

                {/* Profile dropdown */}
                {isProfileOpen && (
                  <div className="absolute right-0 mt-2 w-56 origin-top-right rounded-md border border-zinc-800 bg-zinc-900 py-1 shadow-xl animate-in fade-in slide-in-from-top-5">
                    <div className="border-b border-zinc-800 px-4 py-2">
                      <p className="text-sm font-medium text-white">
                        {user.username}
                      </p>
                      <p className="text-xs text-zinc-400">
                        {user.role === "admin" ? "Administrator" : "Member"}
                      </p>
                    </div>

                    {user.role === "admin" && (
                      <Link
                        href="/admin"
                        className="flex items-center gap-2 px-4 py-2.5 text-sm text-zinc-200 transition hover:bg-zinc-800"
                        onClick={() => setIsProfileOpen(false)}
                      >
                        <svg
                          className="h-4 w-4 text-purple-500"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                          />
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                          />
                        </svg>
                        <span>Admin Panel</span>
                      </Link>
                    )}

                    <Link
                      href="/profile"
                      className="flex items-center gap-2 px-4 py-2.5 text-sm text-zinc-200 transition hover:bg-zinc-800"
                      onClick={() => setIsProfileOpen(false)}
                    >
                      <svg
                        className="h-4 w-4 text-purple-500"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                        />
                      </svg>
                      <span>My Profile</span>
                    </Link>

                    <Link
                      href="/settings"
                      className="flex items-center gap-2 px-4 py-2.5 text-sm text-zinc-200 transition hover:bg-zinc-800"
                      onClick={() => setIsProfileOpen(false)}
                    >
                      <svg
                        className="h-4 w-4 text-purple-500"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                        />
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                        />
                      </svg>
                      <span>Settings</span>
                    </Link>

                    <hr className="my-1 border-zinc-800" />

                    <form action="/api/auth/logout" method="POST">
                      <button
                        type="submit"
                        className="flex w-full items-center px-4 py-2.5 text-left text-sm text-red-400 transition hover:bg-zinc-800"
                      >
                        <svg
                          className="mr-2 h-4 w-4"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
                          />
                        </svg>
                        Sign Out
                      </button>
                    </form>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex items-center gap-2">
                <Link
                  href="/login"
                  className="rounded-md bg-zinc-800/60 px-4 py-2 text-sm font-medium transition duration-200 hover:bg-zinc-700/70"
                >
                  Sign In
                </Link>
                <Link
                  href="/register"
                  className="rounded-md bg-gradient-to-r from-purple-600 to-purple-700 px-4 py-2 text-sm font-medium transition duration-200 hover:from-purple-500 hover:to-purple-600 hover:shadow-md"
                >
                  Sign Up
                </Link>
              </div>
            )}

            {/* Mobile menu button */}
            <button
              className="inline-flex items-center justify-center rounded-md p-2 text-gray-300 hover:bg-zinc-800 hover:text-white md:hidden"
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              aria-expanded={isMenuOpen}
              data-menu-toggle
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                {isMenuOpen ? (
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M6 18L18 6M6 6l12 12"
                  />
                ) : (
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 6h16M4 12h16M4 18h16"
                  />
                )}
              </svg>
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu */}
      {isMenuOpen && (
        <div className="md:hidden" ref={mobileMenuRef}>
          <div className="space-y-1 px-2 pb-3 pt-2">
            {visibleNavItems.map((item) => (
              <Link
                key={item.path}
                href={item.path}
                className={`block rounded-md px-3 py-2 text-base font-medium ${
                  isActive(item.path)
                    ? "bg-purple-900/20 text-purple-400"
                    : "text-gray-300 hover:bg-zinc-800 hover:text-white"
                }`}
                onClick={() => setIsMenuOpen(false)}
              >
                {item.label}
              </Link>
            ))}
          </div>
        </div>
      )}
    </header>
  );
}

// Wrap component with memo for shallow props comparison
export default React.memo(HeaderComponent);

// web/src/lib/components/header.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	// Accept user data as a prop
	let { user } = $props<{ user?: any | null }>();

	// Local state for dropdown menu
	let isProfileMenuOpen = $state(false);

	// Function to toggle dropdown menu
	const toggleProfileMenu = () => {
		isProfileMenuOpen = !isProfileMenuOpen;
	};

	// Close dropdown when clicking outside
	const handleClickOutside = (event: MouseEvent) => {
		const dropdown = document.getElementById('profile-dropdown');
		if (dropdown && !dropdown.contains(event.target as Node) && isProfileMenuOpen) {
			isProfileMenuOpen = false;
		}
	};

	// Setup click listener
	onMount(() => {
		document.addEventListener('click', handleClickOutside);
		return () => document.removeEventListener('click', handleClickOutside);
	});
</script>

<header class="fixed top-0 right-0 left-0 z-50 h-14 w-full bg-zinc-950 px-4 text-white shadow-md">
	<div class="container mx-auto flex h-full items-center justify-between">
		<div class="text-lg font-bold">
			<a href="/" class="flex items-center">
				<span class="text-purple-500">Asthma</span>phobia
			</a>
		</div>
		<nav>
			<ul class="flex items-center space-x-4">
				<li>
					<a href="/" class="text-sm font-medium transition duration-200 hover:text-purple-400"
						>Home</a
					>
				</li>
				<li>
					<a
						href="/dashboard"
						class="text-sm font-medium transition duration-200 hover:text-purple-400"
					>
						Dashboard
					</a>
				</li>

				{#if user}
					<li class="relative" id="profile-dropdown">
						<button
							onclick={toggleProfileMenu}
							class="flex items-center space-x-1 rounded-full bg-zinc-800 px-3 py-1.5 text-sm transition hover:bg-zinc-700"
						>
							<div
								class="flex h-6 w-6 items-center justify-center rounded-full bg-purple-700 text-xs"
							>
								{user.username.charAt(0).toUpperCase()}
							</div>
							<span class="hidden sm:inline">{user.username}</span>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								class="h-4 w-4"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M19 9l-7 7-7-7"
								/>
							</svg>
						</button>

						{#if isProfileMenuOpen}
							<div
								class="absolute right-0 mt-2 w-48 rounded-md border border-zinc-800 bg-zinc-900 py-1 shadow-lg"
							>
								{#if user.role === 'administrator'}
									<a href="/admin" class="block px-4 py-2 text-sm text-zinc-200 hover:bg-zinc-800">
										<div class="flex items-center space-x-2">
											<svg
												xmlns="http://www.w3.org/2000/svg"
												class="h-4 w-4 text-purple-500"
												fill="none"
												viewBox="0 0 24 24"
												stroke="currentColor"
											>
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													stroke-width="2"
													d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
												/>
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													stroke-width="2"
													d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
												/>
											</svg>
											<span>Admin Panel</span>
										</div>
									</a>
								{/if}
								<a href="/user" class="block px-4 py-2 text-sm text-zinc-200 hover:bg-zinc-800">
									<div class="flex items-center space-x-2">
										<svg
											xmlns="http://www.w3.org/2000/svg"
											class="h-4 w-4 text-purple-500"
											fill="none"
											viewBox="0 0 24 24"
											stroke="currentColor"
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
											/>
										</svg>
										<span>My Profile</span>
									</div>
								</a>
								<hr class="my-1 border-zinc-800" />
								<form method="POST" action="/user?/logout">
									<button
										type="submit"
										class="flex w-full items-center px-4 py-2 text-left text-sm text-red-400 hover:bg-zinc-800"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											class="mr-2 h-4 w-4"
											fill="none"
											viewBox="0 0 24 24"
											stroke="currentColor"
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
											/>
										</svg>
										Sign Out
									</button>
								</form>
							</div>
						{/if}
					</li>
				{/if}
			</ul>
		</nav>
	</div>
</header>
